### ISSUE TITLE
external toolchain is for x86_64 only (need one for x86 as well)

### ISSUE THREAD

**Issue by sinseman44** [nezticle/RaspberryPi-BuildRoot#1]
Hi,

The external cross-compiler is built with a 64 bits computer and I can't extecute check cross-compiler with mine. 

Error issue :
Cannot execute cross-compiler '/home/sinseman44/WORK/raspberry_pi/bsquask/host/opt/ext-toolchain/bin/arm-raspberrypi-linux-gnueabi-gcc'
make[1]: **\* [/home/sinseman44/WORK/raspberry_pi/bsquask/stamps/ext-toolchain-checked] Erreur 1
make: **\* [all] Erreur 2

 # file <...>/arm-raspberrypi-linux-gnueabi-gcc 
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.15, stripped

**Comment by nezticle** [comment]
Yes, this is an issue I'm aware of.  I need to generate the x86 version as well.

**Comment by sinseman44** [comment]
I found a config file of crosstool-ng for rapsberry pi, if you want you put it on buildroot. I'll test it before sending it.

**Comment by sagaertj** [comment]
the toolchain is not working on my debian lenny

if you had named it arm-raspberrypi-linux-gnueabi_x64  it would saved me a lot of time figuring out why it does not work.

**Comment by kgrzebien** [comment]
I've created x86 toolchain and prepared small patch for buildroot to use it:
https://github.com/ciptok/RaspberryPi-BuildRoot/commit/a52398a0d2b3383be2d13af6d779a70b260c0e4d

Adding BR2_x86_64=y in configs/raspberrypi_defconfig should allow to use x86_64 toolchain again.

**Comment by nezticle** [comment]
@ciptok I've been trying to integrate x86 support for RaspberryPi-Buildroot using your change, but it turns out your change only works because your use case is in the else.  BR2_x86_64 seems to only be defined when you are building for x86_64 (and where building for armv6), so its always returned as false.  I'm already hosting your x86 toolchain at http://bsquask.com/downloads/toolchains/x86/, but I wont be able to integrate it correctly until I can figure out the correct way to determine the host arch in Buildroot.

**Comment by kgrzebien** [comment]
@nezticle Yeah I've noticed that some time ago just didn't have time to correct it. I'll try to find variable in Buildroot coresponding to host architecture. If I won't manage to do that I'll just create new var to switch between arch manually. Should do it in next week.

**Comment by nezticle** [comment]
Looking at the other external-toolchains in Buildroot, it seems each just downloads the x86 version regardless of the host systems actual arch.  So there probably is not Buildroot variable to check for the host arch, but never-the-less I can probably just throw a system check in there anyway (and fallback to a x86 version if it doesn't detectet x86_64).

something like this: http://www.hastebin.com/sivabufuxo.avrasm

**Comment by nezticle** [comment]
Hopefully this issue should be fixed now with 6d8b117a4cc4566b927b6c63ea1d52300f9d1737 but this needs to be tested further to prove it.

**Comment by nezticle** [comment]
Yes, this logic seems to work on both x86 and x86_64 setups.  Closing this issue.

**Comment by sagaertj** [comment]
Hi  raspi's 

I got it working, but i just have an error  except  when qtdeclarative builds,

 i don't know but i don't think its related to building on x86 all other packages where build .

 I would dive into it but i have no c++ experience,  

[7m>>> qtdeclarative master Building[27m
PATH="/brpi/RaspberryPi-BuildRoot/output/host/bin:/brpi/RaspberryPi-BuildRoot/output/host/usr/bin:/brpi/RaspberryPi-BuildRoot/output
/host/usr/sbin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PERLLIB="/brpi/RaspberryPi-BuildRoot/output/host/usr/lib/perl" /usr/bin/make -j8 -C
/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master
make[1]: Entering directory `/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master'
cd src/ && ( test -f Makefile || /brpi/RaspberryPi-BuildRoot/output/host/usr/bin/qmake
/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master/src/src.pro -o Makefile ) && /usr/bin/make -f Makefile
make[2]: Entering directory`/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master/src'
cd qml/ && ( test -f Makefile || /brpi/RaspberryPi-BuildRoot/output/host/usr/bin/qmake
/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master/src/qml/qml.pro -o Makefile ) && /usr/bin/make -f Makefile
make[3]: Entering directory `/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master/src/qml'
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qqmlinstruction.o qml/qqmlinstruction.cpp
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qquicklistmodel.o qml/qquicklistmodel.cpp
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qquicklistmodelworkeragent.o qml/qquicklistmodelworkeragent.cpp
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qqmlvmemetaobject.o qml/qqmlvmemetaobject.cpp
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qqmlengine.o qml/qqmlengine.cpp
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qqmlexpression.o qml/qqmlexpression.cpp
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qqmlbinding.o qml/qqmlbinding.cpp
/brpi/RaspberryPi-BuildRoot/output/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s
-march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard
--sysroot=/brpi/RaspberryPi-BuildRoot/output/host/usr/arm-unknown-linux-gnueabi/sysroot -O2 -std=c++0x -fvisibility=hidden
-fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fno-exceptions -fPIC -DQT_NO_XCB -DQT_NO_URL_CAST_FROM_STRING
-DQT_NO_INTEGER_EVENT_COORDINATES -DQT_BUILD_QML_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT
-DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_V8_LIB -DV8_SHARED
-DUSING_V8_SHARED -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
-I../../../../host/usr/mkspecs/devices/linux-rasp-pi-g++ -I. -I../../include -I../../include/QtQml -I../../include/QtQml/5.0.0
-I../../include/QtQml/5.0.0/QtQml -Ianimations -I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtNetwork
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtCore/5.0.0/QtCore
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0
-I../../../../host/usr/arm-unknown-linux-gnueabi/sysroot/usr/include/QtV8/5.0.0/QtV8 -I.moc/release-shared -o
.obj/release-shared/qqmlproperty.o qml/qqmlproperty.cpp
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from qml/qquicklistmodelworkeragent_p.h:61,
                 from qml/qquicklistmodelworkeragent.cpp:42:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from qml/qqmlexpression_p.h:58,
                 from qml/qqmlexpression.cpp:43:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmlengine_p.h:82,
                 from ../../include/QtQml/5.0.0/QtQml/private/qqmlengine_p.h:1,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmljavascriptexpression_p.h:59,
                 from ../../include/QtQml/5.0.0/QtQml/private/qqmljavascriptexpression_p.h:1,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmlbinding_p.h:69,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmlcustomparser_p.h:59,
                 from ../../include/QtQml/5.0.0/QtQml/private/qqmlcustomparser_p.h:1,
                 from qml/qquicklistmodel_p.h:46,
                 from qml/qquicklistmodel_p_p.h:56,
                 from qml/qquicklistmodel.cpp:42:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmlengine_p.h:82,
                 from ../../include/QtQml/5.0.0/QtQml/private/qqmlengine_p.h:1,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmljavascriptexpression_p.h:59,
                 from ../../include/QtQml/5.0.0/QtQml/private/qqmljavascriptexpression_p.h:1,
                 from qml/qqmlbinding_p.h:69,
                 from qml/qqmlbinding.cpp:42:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmlengine_p.h:82,
                 from ../../include/QtQml/5.0.0/QtQml/private/qqmlengine_p.h:1,
                 from ../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/qqmljavascriptexpression_p.h:59,
                 from ../../include/QtQml/5.0.0/QtQml/private/qqmljavascriptexpression_p.h:1,
                 from qml/qqmlbinding_p.h:69,
                 from qml/qqmlproperty.cpp:46:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from qml/qqmlengine_p.h:82,
                 from qml/qqmlcompiler_p.h:61,
                 from qml/qqmlinstruction.cpp:44:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from qml/qqmlengine_p.h:82,
                 from qml/qqmlcompiler_p.h:61,
                 from qml/qqmlvmemetaobject_p.h:68,
                 from qml/qqmlvmemetaobject.cpp:42:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
In file included from ../../include/QtQml/5.0.0/QtQml/private/qv8engine_p.h:1:0,
                 from qml/qqmlengine_p.h:82,
                 from qml/qqmlengine.cpp:42:
../../include/QtQml/5.0.0/QtQml/private/../../../../../src/qml/qml/v8/qv8engine_p.h:621:13: error: template-id
'qHash<v8::Handle<v8::Object> >' for 'uint qHash(const v8::Handle<v8::Object>&, uint)' does not match any template declaration
make[3]: *** [.obj/release-shared/qquicklistmodelworkeragent.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [.obj/release-shared/qqmlvmemetaobject.o] Error 1
make[3]: *** [.obj/release-shared/qqmlinstruction.o] Error 1
make[3]: *** [.obj/release-shared/qqmlbinding.o] Error 1
make[3]: *** [.obj/release-shared/qqmlexpression.o] Error 1
make[3]: *** [.obj/release-shared/qqmlproperty.o] Error 1
make[3]: *** [.obj/release-shared/qquicklistmodel.o] Error 1
make[3]: *** [.obj/release-shared/qqmlengine.o] Error 1
make[3]: Leaving directory`/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master/src/qml'
make[2]: **\* [sub-qml-make_first-ordered] Error 2
make[2]: Leaving directory `/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master/src'
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory`/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master'
make: **\* [/brpi/RaspberryPi-BuildRoot/output/build/qtdeclarative-master/.stamp_built] Error 2

---

Van: Andy Nichols [ mailto:notifications@github.com mailto:notifications@github.com]
Verzonden: dinsdag 21 augustus 2012 10:42
Aan: nezticle/RaspberryPi-BuildRoot
Onderwerp: Re: [RaspberryPi-BuildRoot] external toolchain is for x86_64 only (need one for x86 as well) (#1)

Yes, this logic seems to work on both x86 and x86_64 setups. Closing this issue.

## 

Reply to this email directly or view it on GitHub <
https://github.com/nezticle/RaspberryPi-BuildRoot/issues/1#issuecomment-7895018
https://github.com/nezticle/RaspberryPi-BuildRoot/issues/1#issuecomment-7895018> .

 < https://github.com/notifications/beacon/2q-YndLOrWSPgJunk3yRVJv3za796yfga6EmUTxsgKJWyK5HGigje2waFaLzTaqX.gif
https://github.com/notifications/beacon/2q-YndLOrWSPgJunk3yRVJv3za796yfga6EmUTxsgKJWyK5HGigje2waFaLzTaqX.gif>

**Comment by nezticle** [comment]
@sagaertj I don't think this is an issue with the x86 toolchain in particular, but rather a separate issue where the Qt packages should not be pulling from the "master" branches (but rather individual sha's).  I was waiting for the Qt 5.0 Beta to come out before doing this, but I think its important for the sake of consistency to do this already.  I think there is an incompatibility between the qtdeclarative and qtjsbackend packages you pulled.  To re-do this you would have to delete both the build/qtdeclarative-master and build/qtjsbackend folders as well as the tarballs that are created from the Git repos in the "dl" folder (something like dl/qtjsbackend-master.tar.gz and dl/qtdeclarative-master.tar.gz) then run make again.

I opened a new issue for this.

**Comment by sagaertj** [comment]
Hi

Ok, will try to rebuild, i agree using the master is a bad idea, because you can never be sure of the version that will be build,
and if you do a rebuild of a configuration one made a few years ago, you could end up with some nasty hard to track build errors in
other packages that rely on these.

An option in the buildroot config would be nice where you could select the master or a  known stable hash version.

Kind regards, Johan

---

Van: Andy Nichols [mailto:notifications@github.com] 
Verzonden: dinsdag 21 augustus 2012 20:38
Aan: nezticle/RaspberryPi-BuildRoot
Onderwerp: Re: [RaspberryPi-BuildRoot] external toolchain is for x86_64 only (need one for x86 as well) (#1)

I don't think this is an issue with the x86 toolchain in particular, but rather a separate issue where the Qt packages should not be
pulling from the "master" branches (but rather individual sha's). I was waiting for the Qt 5.0 Beta to come out before doing this,
but I think its important for the sake of consistency to do this already. I think there is an incompatibility between the
qtdeclarative and qtjsbackend packages you pulled. To re-do this you would have to delete both the build/qtdeclarative-master and
build/qtjsbackend folders as well as the tarballs that are created from the Git repos in the "dl" folder (something like
dl/qtjsbackend-master.tar.gz and dl/qtdeclarative-master.tar.gz) then run make again.

## 

Reply to this email directly or view  https://github.com/nezticle/RaspberryPi-BuildRoot/issues/1#issuecomment-7911351 it on
GitHub. 

  https://github.com/notifications/beacon/2q-YndLOrWSPgJunk3yRVJv3za796yfga6EmUTxsgKJWyK5HGigje2waFaLzTaqX.gif
