### ISSUE TITLE
Use systemd

### ISSUE THREAD

**Issue by nezticle** [nezticle/RaspberryPi-BuildRoot#10]
Right now were bringing the userspace up with sysvinit, but only because I've not been able to get systemd to work.  Ideally we should use systemd.

**Comment by ghost** [comment]
Default busybox config for busybox 1.20.x provides init, yet sysvinit is needed (bb can't read this style initttab).

When "make busybox-menuconfig" is ran and the target is build, the sysvinit is replaced by busybox and the system won't be able to boot

Until systemd is working, disable busybox's init and use sysvinit.

**Comment by nezticle** [comment]
@limpens Thank you for this information.  This actually explains the behavior I've observed currently with init.

**Comment by nezticle** [comment]
I've been testing with systemd, it does work now, but still requires some configuring of how the services are started.

**Comment by nezticle** [comment]
I actually have upstart working now in the bsquask branch.  I think I like how that works better than systemd anyway.
