### ISSUE TITLE
Package omxplayer

### ISSUE THREAD

**Issue by nezticle** [nezticle/RaspberryPi-BuildRoot#11]
This is the media player designed for the Raspberry Pi, and is the media player backend for XBMC.

**Comment by nezticle** [comment]
Right now it doesn't completely fit with the Bsquask SDK, because it requires several additional libraries that overlap with Qt 5, so I will do a bit of massaging in https://github.com/nezticle/omxplayer to get it working correctly while keeping with the lightweight nature of Bsquask.

**Comment by nezticle** [comment]
Update:  I have omxplayer working now, so now its just a matter of packaging it up in buildroot.

**Comment by nezticle** [comment]
omxplayer should be built now as of b330a344626561817c78eedd91da3b0e7b948255
you probably still need to pass the "--adev hdmi" argument to get sound though.  I watched a 1080p movie while testing and saw only 13% CPU usage, so I'm quite happy with it.

**Comment by nezticle** [comment]
I should also mention that it still isn't built by default.  Its quite small (and really nice for showing off) so I may enable that tomorrow.

**Comment by SnobGoblin** [comment]
Hey, good stuff!  The place I was talking about where you can download video with master audio in 7.1 is this one: http://www.demo-world.eu/trailers/high-definition-trailers.php .

**Comment by nezticle** [comment]
I case anyone's interested.  I tested the HD DTS animated logo lossless with 7.1 HD-MA with omxplayer.  The result was that it played, but because the CPU usage was 100%, the video/audio did stutter.  This is because the audio processing is unaccelerated, and we are CPU bound processing 8 channels of audio.

**Comment by nezticle** [comment]
@SnobGoblin With the new overclocking settings I'm testing, I can play the HD DTS animated logo lossless with 7.1 HD-MA with omxplayer without the stuttering.  90% CPU usage, but smooth playback none-the-less.
