### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by proydakov** [nezticle/RaspberryPi-BuildRoot#14]
When using buildroot mode xconfig - I can save settings. If I use the command "make raspberrypi_defconfig O = $ BSQUASK_DIR xconfig'" apply the settings, but the settings do not appear when reopen. How can I best add config assembly required me to the library?

**Comment by nezticle** [comment]
The trick to configuring is to first generate the config with "make raspberrypi_defconfig" then run "make xconfig".  If you build with the output directory option, "cd" to that directory first then run "make xconfig" there.  make raspberrypi_defconfig is just generating a ".config" file from the defconfig, so as long as that file exists, make xconfig (or menuconfig) should work.

**Comment by proydakov** [comment]
Understood. All works. Thanks.
