### ISSUE TITLE
Package Qt 5.0.0 Release from tar.gz files

### ISSUE THREAD

**Issue by nezticle** [nezticle/RaspberryPi-BuildRoot#19]
Right now we pull each Qt 5 module down from git repos for a few selected repositories.  Once Qt 5.0.0 is released we should use the submodule packages instead, which should speed up the download process, and makes more sense to package a release.

The following submodules should be packaged:
qtbase
qtxmlpatterns
qtjsbackend
qtdeclarative
qtmultimedia
qtgraphicaleffects
qtimageformats
qtquick1
qtsvg
qtscript
qtwebkit
qtwebkit-examples-and-demos

qt3d and qtwayland are not part of the release, so these will still need to be built from git.

In addition, there should be an examples option for each package that should determine whether or not to build and deploy the qt examples to the image.

**Comment by inadsan** [comment]
Hello nezticle,

A small change in qtbase.mk to be a little more consistent.
On line 17 change:
-device-option CROSS_COMPILE=$(HOST_DIR)/usr/bin/arm-raspberrypi-linux-gnueabi- \
by:
-device-option CROSS_COMPILE=$(TARGET_CROSS) \

Sorry for not doing a pull request, but not much use git.
Great job and thanks for QT5 approach to raspberry.
greetings

**Comment by nezticle** [comment]
@inadsan thanks for the tip

**Comment by inadsan** [comment]
And another change on packages QT5:
Change the copy from the STAGING_DIR to BUILD directory:
        cp -dpf $(@D)/lib/libQt5_.so._ $(TARGET_DIR)/usr/lib
        cp -dpfr $(@D)/plugins $(TARGET_DIR)/usr
        cp -dpfr $(@D)/lib/fonts $(TARGET_DIR)/usr/lib

This prevents copy things from other packages when qtbase recompile.

For many people it is the same but for me not because I've made ​​some modifications to create packages opk and I mix files.

greetings

**Comment by nezticle** [comment]
Both suggestions for the Qt 5 packages are now in master.

**Comment by nezticle** [comment]
Qt 5.0.0 release has been packaged
