### ISSUE TITLE
Add 'kbd' by default

### ISSUE THREAD

**Issue by ghost** [nezticle/RaspberryPi-BuildRoot#24]
'kbd' provides the command 'loadkeys' used to load many keyboard layouts. It would be useful for those (like me) that use other layouts than the default English one. It can be easily checked in buildroot.

**Comment by ghost** [comment]
There is also the tool 'loadkmap' from busybox, but I don't know if it provides layouts in /etc folder ready to use...!

**Comment by nezticle** [comment]
kdb package has been added to raspberrypi_defconfig in 64f303a70dc904157e6f7ee56563ed2e3389ed09
