### ISSUE TITLE
Beecrypt

### ISSUE THREAD

**Issue by Pwolfger** [nezticle/RaspberryPi-BuildRoot#25]
Hi,
today I tried to compile rpm, which depends on beecrypt. However it always failed with the following error:
/home/paul/raspberry/bsquask/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libbeecrypt.so: undefined reference to `mpaddsqrtrc'
/home/paul/raspberry/bsquask/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libbeecrypt.so: undefined reference to`mpaddmul'
/home/paul/raspberry/bsquask/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libbeecrypt.so: undefined reference to `mpsetmul'

objdump -T staging/usr/lib/libbeecrypt.so.7.0.0 revealed that there really was an undefined reference to these three functions, although they are present in source file build/beecrypt-4.2.1/mp.c
My dirty fix was just to remove the preprocessor statements from the three concerned functions.
Now it seems to work, at least objdump doesn't report them as missing and rpm got also configured successfully.

Kind regards,
Paul

**Comment by nezticle** [comment]
I remember seeing this error when I first started this project (though at the time I wasn't comfortable enough with BuildRoot to try and fix it at the time). I'll take a look and see what can be done.

**Comment by nezticle** [comment]
Seems to be fixed as of the last update from upstream BuildRoot.
