### ISSUE TITLE
I cant git clone.

### ISSUE THREAD

**Issue by nospamcalfee** [nezticle/RaspberryPi-BuildRoot#26]
Following your directions:

 git clone git@github.com:nezticle/RaspberryPi-BuildRoot.git BuildRoot
Cloning into 'BuildRoot'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

Any ideas?

**Comment by thewizster** [comment]
You need to do this first:
https://help.github.com/articles/generating-ssh-keys

**Comment by paul-c** [comment]
For anonymous clones, the instructions are wrong. It should read:

git clone git://github.com/nezticle/RaspberryPi-BuildRoot.git BuildRoot

**Comment by nezticle** [comment]
@paul-c Thanks for updating the wiki, I updated the README.md file that shows up on the front page as well.
