### ISSUE TITLE
Libcurl vs Openssl

### ISSUE THREAD

**Issue by Pwolfger** [nezticle/RaspberryPi-BuildRoot#28]
In the current master (libcurl 7.27.0,  openssl-1.0.1c) building libcurl with openssl support isn't working.
I get the following error:
$ libcurl.so: undefined reference to `SSL_CTX_set_srp_password'

It did work before with libcurl 7.25.0 and an older openssl version, however I don't remember the version.

For now I disabled openssl support for libcurl and it builds.

I'm sorry that I only post errors but unfortunately I don't know how to fix them at all.

Regards,
Paul

**Comment by nezticle** [comment]
I can't reproduce this error with the latest version, seems to be fixed now in upstream BuildRoot
