### ISSUE TITLE
device_table.txt not found

### ISSUE THREAD

**Issue by Pwolfger** [nezticle/RaspberryPi-BuildRoot#29]
Another small issue: 
While "Generating root filesystem image rootfs.tar" the script looks for the device table in target/generic/device_table.txt (and generating fails) although it moved to system/device_table.txt .

Regards,
Paul

**Comment by nezticle** [comment]
I merged in my work in the bsquask branch, which fixed this where device_table.txt is copied from board/raspberrypi/device_table.txt
