### ISSUE TITLE
Building QtWebKit: reference to /home/nezticle

### ISSUE THREAD

**Issue by pepeki** [nezticle/RaspberryPi-BuildRoot#38]
Hello,
I changed /opt/bsquask/.config file (BR2_PACKAGE_QTWEBKIT=y), I have been compiling the QtWebKit code for a second day. And when I finally arrived to a linking phase, I got an error... :(

Here's part of it:

/opt/bsquask/host/opt/ext-toolchain/bin/../lib/gcc/arm-raspberrypi-linux-gnueabi/4.6.3/../../../../arm-raspberrypi-linux-gnueabi/bin/ld: BFD (crosstool-NG hg+default-1f6c8e4b2b92) 2.22 assertion fail /home/nezticle/Devices/RaspberryPi/toolchain/i386-raspberrypi/.build/src/binutils-2.22/bfd/elf32-arm.c:12049
...
collect2: ld returned 1 exit status
make[4]: **\* [../lib/libQt5WebKit.so.5.0.1] Error 1
make[3]: **\* [sub-api-pri-make_first-ordered] Error 2
make[2]: **\* [sub-Source-QtWebKit-pro-make_first-ordered] Error 2
make[1]: **\* [/opt/bsquask/build/qtwebkit-5.0.1/.stamp_built] Error 2
make: **\* [all] Error 2

When I searched for "/home/nezticle" references in filesystem - I found multiple config.log files referencing:
     /home/nezticle/Devices/RaspberryPi/toolchain/i386-raspberrypi/.build/

Is there anything wrong with my environment?
Please don't tell me - I have to go through the whole compilation again...
Can I fix it with some symbolic link?

Thanks a lot,
Peter

**Comment by nezticle** [comment]
I suspect the linker failed because you don't have enough memory available to link WebKit.  Someone reported a similar bug here before, and turns out they were trying to build in a virtual machine with only 512mb of RAM and linking WebKit used all available RAM and swap available then crashed.  It may also explain why your build was taking so long (by having to use swap memory constantly).  If you are also building in a virtual machine, allocate more RAM, or if you can't, or are not using a virtual machine, at least increase the size of your swap file/partion.

WebKit is huge, and this is a problem that is seen outside of this build environment as well.

**Comment by pepeki** [comment]
Hi,
I am running ubuntu 12.10 in VirtualBox with 2GB RAM assigned to it... Yes - I had troubles compiling it with 1GB RAM - therefore I had changed it into 2GB...
I can try to boost it up even more - but how on earth does it fail referencing the path "/home/nezticle/Devices/..."?
I will try to boost the memory up a bit more and will report the result..

Thanks,
Peter

**Comment by nezticle** [comment]
The reason you are seeing references to my(nezticle's) file system here is because there was an assert in the linker process and it is trying to tell you what line it asserted on, but since the linker was built on one of my machines it can't fine the path to the linker source code.  This wouldn't have helped you very much either though.  

I'm not sure of the exact amount of ram it takes to like WebKit these days (I test builds on machines with at least 4GB of ram) but a couple years ago builds of WebKit would fail on machines without 2GB of free ram and swap.

## 

Andy Nichols

**Comment by pepeki** [comment]
OK - I have increased the MEM and now I get the following:

/opt/bsquask/build/qtwebkit-5.0.1/Source/WebCore/release/libWebCore.a(JSSVGEleme
ntWrapperFactory.o): In function `WebCore::JSDOMWrapper* WebCore::createWrapper<
WebCore::JSSVGFEColorMatrixElement, WebCore::SVGFEColorMatrixElement>(JSC::ExecS
tate*, WebCore::JSDOMGlobalObject*, WebCore::SVGFEColorMatrixElement*)':
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_25JSSVGFECol
orMatrixElementENS_23SVGFEColorMatrixElementEEEPNS_12JSDOMWrapperEPN3JSC9ExecSta
teEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper* WebCore::createWrapper<We
bCore::JSSVGFEColorMatrixElement, WebCore::SVGFEColorMatrixElement>(JSC::ExecSta
te*, WebCore::JSDOMGlobalObject*, WebCore::SVGFEColorMatrixElement*)]+0x8c): und
efined reference to`WebCore::JSSVGFEColorMatrixElement::JSSVGFEColorMatrixEleme
nt(JSC::Structure_, WebCore::JSDOMGlobalObject_, WTF::PassRefPtr<WebCore::SVGFEC
olorMatrixElement>)'
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_25JSSVGFECol
orMatrixElementENS_23SVGFEColorMatrixElementEEEPNS_12JSDOMWrapperEPN3JSC9ExecSta
teEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper\* WebCore::createWrapper<We
bCore::JSSVGFEColorMatrixElement, WebCore::SVGFEColorMatrixElement>(JSC::ExecSta
te_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEColorMatrixElement_)]+0xb4): und
efined reference to `WebCore::JSSVGFEColorMatrixElement::finishCreation(JSC::JSG
lobalData&)'
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_25JSSVGFECol
orMatrixElementENS_23SVGFEColorMatrixElementEEEPNS_12JSDOMWrapperEPN3JSC9ExecSta
teEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper_ WebCore::createWrapper<We
bCore::JSSVGFEColorMatrixElement, WebCore::SVGFEColorMatrixElement>(JSC::ExecSta
te_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEColorMatrixElement_)]+0x184): un
defined reference to `WebCore::JSSVGFEColorMatrixElement::createPrototype(JSC::E
xecState_, JSC::JSGlobalObject_)'
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_25JSSVGFECol
orMatrixElementENS_23SVGFEColorMatrixElementEEEPNS_12JSDOMWrapperEPN3JSC9ExecSta
teEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper_ WebCore::createWrapper<We
bCore::JSSVGFEColorMatrixElement, WebCore::SVGFEColorMatrixElement>(JSC::ExecSta
te_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEColorMatrixElement_)]+0x248): un
defined reference to `WebCore::JSSVGFEColorMatrixElement::s_info'
/opt/bsquask/build/qtwebkit-5.0.1/Source/WebCore/release/libWebCore.a(JSSVGEleme
ntWrapperFactory.o): In function`WebCore::JSDOMWrapper_ WebCore::createWrapper<
WebCore::JSSVGFEDisplacementMapElement, WebCore::SVGFEDisplacementMapElement>(JS
C::ExecState_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEDisplacementMapElement
_)':
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_29JSSVGFEDis
placementMapElementENS_27SVGFEDisplacementMapElementEEEPNS_12JSDOMWrapperEPN3JSC
9ExecStateEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper_ WebCore::createWr
apper<WebCore::JSSVGFEDisplacementMapElement, WebCore::SVGFEDisplacementMapEleme
nt>(JSC::ExecState_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEDisplacementMapE
lement_)]+0x8c): undefined reference to `WebCore::JSSVGFEDisplacementMapElement:
:JSSVGFEDisplacementMapElement(JSC::Structure_, WebCore::JSDOMGlobalObject_, WTF
::PassRefPtrWebCore::SVGFEDisplacementMapElement)'
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_29JSSVGFEDis
placementMapElementENS_27SVGFEDisplacementMapElementEEEPNS_12JSDOMWrapperEPN3JSC
9ExecStateEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper_ WebCore::createWr
apper<WebCore::JSSVGFEDisplacementMapElement, WebCore::SVGFEDisplacementMapEleme
nt>(JSC::ExecState_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEDisplacementMapE
lement_)]+0xb4): undefined reference to `WebCore::JSSVGFEDisplacementMapElement:
:finishCreation(JSC::JSGlobalData&)'
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_29JSSVGFEDis
placementMapElementENS_27SVGFEDisplacementMapElementEEEPNS_12JSDOMWrapperEPN3JSC
9ExecStateEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper_ WebCore::createWr
apper<WebCore::JSSVGFEDisplacementMapElement, WebCore::SVGFEDisplacementMapEleme
nt>(JSC::ExecState_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEDisplacementMapE
lement_)]+0x184): undefined reference to `WebCore::JSSVGFEDisplacementMapElement
::createPrototype(JSC::ExecState_, JSC::JSGlobalObject_)'
JSSVGElementWrapperFactory.cpp:(.text._ZN7WebCore13createWrapperINS_29JSSVGFEDis
placementMapElementENS_27SVGFEDisplacementMapElementEEEPNS_12JSDOMWrapperEPN3JSC
9ExecStateEPNS_17JSDOMGlobalObjectEPT0_[WebCore::JSDOMWrapper_ WebCore::createWr
apper<WebCore::JSSVGFEDisplacementMapElement, WebCore::SVGFEDisplacementMapEleme
nt>(JSC::ExecState_, WebCore::JSDOMGlobalObject_, WebCore::SVGFEDisplacementMapE
lement_)]+0x248): undefined reference to `WebCore::JSSVGFEDisplacementMapElement
::s_info'
/opt/bsquask/build/qtwebkit-5.0.1/Source/WebCore/release/libWebCore.a(JSDOMWindo
w.o): In function`WebCore::jsDOMWindowSVGFEDisplacementMapElementConstructor(JS
C::ExecState_, JSC::JSValue, JSC::PropertyName)':
JSDOMWindow.cpp:(.text._ZN7WebCore49jsDOMWindowSVGFEDisplacementMapElementConstr
uctorEPN3JSC9ExecStateENS0_7JSValueENS0_12PropertyNameE+0x44): undefined referen
ce to `WebCore::JSSVGFEDisplacementMapElement::getConstructor(JSC::ExecState*, J
SC::JSGlobalObject*)'
/opt/bsquask/build/qtwebkit-5.0.1/Source/WebCore/release/libWebCore.a(JSDOMWindo
w.o): In function`WebCore::jsDOMWindowSVGFEColorMatrixElementConstructor(JSC::E
xecState_, JSC::JSValue, JSC::PropertyName)':
JSDOMWindow.cpp:(.text._ZN7WebCore45jsDOMWindowSVGFEColorMatrixElementConstructo
rEPN3JSC9ExecStateENS0_7JSValueENS0_12PropertyNameE+0x44): undefined reference t
o `WebCore::JSSVGFEColorMatrixElement::getConstructor(JSC::ExecState_, JSC::JSGl
obalObject*)'

This seems like there is inconsistency of some sort in the source code...

Do you have any quick idea?

In meantime - I will continue troubleshooting this..

Thanks,
Peter

**Comment by nezticle** [comment]
I am building bsquask + qtwebkit in a clean virtual machine now to double check things.  My test setup is x86 Ubuntu 12.04, with 4 x CPU and 2Gb or ram and 2Gb of swap.  It just started building qtwebkit, so I'll know how it went in about an hour.

**Comment by nezticle** [comment]
Well, everything built fine, including QtWebkit.  I suspect that in your case the libWebCore.a archive existed from when your linker failed before and Make assumed that that step was done, but since it was incomplete it did not contain all the symbols needed when it was linked later.  I hate to say it, as I know how insanely long it takes to build, but you make need to rebuild qtwebkit from a clean start.  The "quickest" way is just just delete the build/qtwebkit\* folder in your bsquask directory and run "make" again, to build qtwebkit from a clean start.  Hopefully that will resolve your issue.

**Comment by pepeki** [comment]
Hello,
thanks a lot for your help. I did the clean build with increased RAM and with one added CPU core and was able to build it in less than 6hours.

It's time to test it now...  :)

Thanks again,
Peter
