### ISSUE TITLE
python 3.3

### ISSUE THREAD

**Issue by Tibalt** [nezticle/RaspberryPi-BuildRoot#42]
do you guys have a plan to add python 3.3 on bsquask?

**Comment by nezticle** [comment]
I'm pretty sure its already there, just not in the default generated image.  If you run "make python3" it should build python 3.3 and then if you run "make" again, it should generate you a new image that includes python 3.3.

**Comment by nezticle** [comment]
If you are requesting that it be included in the default image, that's a possibility as well

**Comment by Tibalt** [comment]
OK.
Be included in the default image is not very necessary. I guess to copy the compiled python3 related libs and bins(/opt/bsquask/target/usr/bin and /opt/bsquask/target/usr/lib) to the sd card also would work?
Besides, I wonder how could I select the modules such as ssl for python3?
