### ISSUE TITLE
make of bsquask failed

### ISSUE THREAD

**Issue by steffend-gsp** [nezticle/RaspberryPi-BuildRoot#44]
The make process is broken.

make[1]: **\* [/opt/RaspberryPi-BuildRoot/bsquask/build/VideoCore-"0e57896bbe98a0885506c3c09821d2c3c4465eef"/.stamp_downloaded] Fehler 1

Booth destinations are not available. Can you help please ?!

http://github.com/raspberrypi/userland/tarball/master/VideoCore-0e57896bbe98a0885506c3c09821d2c3c4465eef.tar.gz

http://sources.buildroot.net//VideoCore-0e57896bbe98a0885506c3c09821d2c3c4465eef.tar.gz

**Comment by ghost** [comment]
I've just tried the VideoCore from github, this download completes without any problems from my location.
You could always change the revision using make menuconfig and enter the latest release (the latest GitHub release for that repository).
