### ISSUE TITLE
Changes to config.txt don't appear to work

### ISSUE THREAD

**Issue by johnthesoftware** [nezticle/RaspberryPi-BuildRoot#48]
As per the title. I haven't tested all of them. I want to change sdtv_mode to 2 but it stays at zero (vcgencmd).  Similarly, disable_overscan stays at 1.  I've dug through the source but drawn a blank.

Everything else is great, really fast boot, really easy to add new stuff. Thanks.

**Comment by ghost** [comment]
Please elaborate. Changes in your /boot directory or to a file in your build environment?
To change on the RPI, you'll probably have you mount the boot partition prior to editing. /boot contains files but this probably isn't your boot partition.

**Comment by johnthesoftware** [comment]
Hi limpens,

That was a damn quick response!

/boot/config.txt on the SD card.  After changing /boot/config.txt on the RPi SD card and rebooting, the changes I made are still in /boot/config.txt eg. sdtv_mode=2, but vcgencmd get_config sdtv_cmd returns sdtv_mode=0, and the output is still NTSC.

This is the same for other parameters I've changed too.  The format is as recommended (one entry per line)

John

**Comment by johnthesoftware** [comment]
Crap. Closed this by accident

**Comment by johnthesoftware** [comment]
Sorted.  Thanks limpen as you said /boot isn't my boot partition.  Confirmed bootable partition using fdisk buried in /dev/disk subdirectories.  Mounted /dev/disk/by-id/mm-NCard_0xloadsofnumbers-part1 as /mnt edited saved rebooted, sdtv_mode now = 2.  All new to me.

John

**Comment by johnthesoftware** [comment]
Not out of the woods yet.  sdtv_mode  has no effect. Others do, for example the overscan ones, but whatever I set sdtv_mode to it's still NTSC.  vcgencmd confirms that sdtv_mode=2.

**Comment by ghost** [comment]
Did you change the sdtv_mode in config.txt ? (see http://elinux.org/RPiconfig#Video_mode_options)
Is your display connected to HDMI or the Composite plug? My best guess is that the sdtv_ stuff only is relevant for the composite connection.

You _are_ using a recent version of the RPI firmware?

**Comment by johnthesoftware** [comment]
sdtv_mode=2 in config.txt on the mounted boot partition /dev/disk/by-label/boot.

I built the boot and rootfs images about a week ago.  I assume that the most recent firmware was downloaded at that time.  I'm using the composite output for my target hardware. All development work was done on HDMI. It is now disconnected.  My target hardware supports NTSC and PAL (this is only relevant for composite video and has no meaning for HDMI), however it does not work correctly in NTSC (enough for debug) which is why I need to switch to PAL.  I have had the PAL output working using a Raspbian distribution.

**Comment by ghost** [comment]
The buildroot environment doesn't new firmware, just the version configured using make menuconfig.

When vcgencmd reports a different value than configured, it looks like a typo or some other value overriding it.

Did you have any success changing stuff and have vcgencmd report correct values?

**Comment by johnthesoftware** [comment]
Yes, I fixed the first problem, if I change sdtv_mode to 2, vcgencmd reports sdtv_mode=2.  I reported this a few comments back.

Although vcgencmd reports sdtv_mode=2, the AV output is still NTSC.  However, if I change the overscan commands these DO have an effect, so I know that at least some of config.txt is working

**Comment by johnthesoftware** [comment]
hdmi_ignore_hotplug also works.
