### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by mfoerst** [nezticle/RaspberryPi-BuildRoot#49]
Hi,
I was trying to create an image for my RasPi, following the instructions. At the step "make" my computer compiled for about half an hour and then returned this error message:

/opt/bsquask/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/arm-raspberrypi-linux-gnueabi -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/lib/arm-raspberrypi-linux-gnueabi --sysroot=/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/usr/lib -shared -o libqnmbearer.so .obj/release-shared/main.o .obj/release-shared/qnmdbushelper.o .obj/release-shared/qnetworkmanagerservice.o .obj/release-shared/qnetworkmanagerengine.o .obj/release-shared/qnetworksession_impl.o .obj/release-shared/moc_qnmdbushelper.o .obj/release-shared/moc_qnetworkmanagerservice.o .obj/release-shared/moc_qnetworkmanagerengine.o .obj/release-shared/moc_qnetworksession_impl.o .obj/release-shared/moc_qbearerengine_impl.o  -L/opt/bsquask/build/qtbase-5.0.1/lib -lQt5DBus -lQt5Network -lQt5Core -lpthread  
mv -f libqnmbearer.so ../../../../plugins/bearer/
make[3]: **\* [sub-plugins-make_first] Error 2
make[2]: **\* [sub-src-make_first] Error 2
make[1]: **\* [/opt/bsquask/build/qtbase-5.0.1/.stamp_built] Error 2
make: **\* [all] Error 2

I already googled about this error but didn't found anything useful.

Has anyone an idea how to fix this error?

Im running Ubuntu 12.04 32bit in a VM on a Windows machine.

Thx

**Comment by lederer** [comment]
Same here. I've also tried building it with later qt releases, like official 5.1.0 or development 5.1.0-rc2, but it still always fails during the qt portion of the build, just at a different point:

mv -f libqevdevkeyboardplugin.so ../../../../plugins/generic/ 
mv -f libqevdevtabletplugin.so ../../../../plugins/generic/ 
make[3]: **\* [sub-plugins-make_first] Error 2
make[2]: **\* [sub-src-make_first] Error 2
make[1]: **\* [/opt/bsquask/build/qtbase-5.1.0/.stamp_built] Error 2
make: **\* [all] Error 2

Ubuntu 12.04 64bit with 8G RAM

**Comment by johnthesoftware** [comment]
same here...

A previous build worked ok but after re-gitting yesterday I get this...

../../../../mkspecs/devices/linux-rasp-pi-g++/qeglfshooks_pi.cpp:95:68: error: declaration of C function 'int vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T, DISPMANX_ELEMENT_HANDLE_T, uint32_t, int32_t, uint8_t, const VC_RECT_T_, const VC_RECT_T_, DISPMANX_RESOURCE_HANDLE_T, VC_IMAGE_TRANSFORM_T)' conflicts with
/opt/RPi-Enforcer-Bsquask/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include/interface/vmcs_host/vc_dispmanx.h:108:22: error: previous declaration 'int vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T, DISPMANX_ELEMENT_HANDLE_T, uint32_t, int32_t, uint8_t, const VC_RECT_T_, const VC_RECT_T_, DISPMANX_RESOURCE_HANDLE_T, DISPMANX_TRANSFORM_T)' here
../../../../mkspecs/devices/linux-rasp-pi-g++/qeglfshooks_pi.cpp:195:10: warning: unused parameter 'window' [-Wunused-parameter]
./qeglfshooks.h:74:21: warning: 'hooks' defined but not used [-Wunused-variable]
make[6]: **\* [.obj/release-shared/qeglfshooks_pi.o] Error 1
make[5]: **\* [sub-eglfs-make_first] Error 2
make[4]: **\* [sub-platforms-make_first] Error 2
make[3]: **\* [sub-plugins-make_first] Error 2
make[2]: **\* [sub-src-make_first] Error 2
make[1]: **\* [/opt/RPi-Enforcer-Bsquask/bsquask/build/qtbase-5.0.1/.stamp_built] Error 2

I can confirm that the file content conflicts listed do not exist in the previous version.

John

**Comment by hwarner1211** [comment]
Same here... Also, qtbase 5.0.1 is no longer available.

/opt/bsquask/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/arm-raspberrypi-linux-gnueabi -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/lib/arm-raspberrypi-linux-gnueabi --sysroot=/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/usr/lib -shared -o libqsqlite.so .obj/release-shared/smain.o .obj/release-shared/qsql_sqlite.o .obj/release-shared/sqlite3.o .obj/release-shared/moc_qsql_sqlite.o  -L/opt/bsquask/build/qtbase-5.0.1/lib -lQt5Sql -lQt5Core -lpthread  
mv -f libqsqlite.so ../../../../plugins/sqldrivers/
make[3]: **\* [sub-plugins-make_first] Error 2
make[2]: **\* [sub-src-make_first] Error 2
make[1]: **\* [/opt/bsquask/build/qtbase-5.0.1/.stamp_built] Error 2
make: **\* [all] Error 2

**Comment by nezticle** [comment]
Noted, will push an update as soon as possible

**Comment by nezticle** [comment]
Ok, I pushed an official 5.1.0 upgrade.  I hope that this fixes all current build issues.

**Comment by lederer** [comment]
Thanks for the update. Unfortunately I'm still in the same boat:

mv -f libqevdevkeyboardplugin.so ../../../../plugins/generic/ 
rm -f libqevdevtabletplugin.so
/opt/bsquask/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/arm-raspberrypi-linux-gnueabi -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/lib/arm-raspberrypi-linux-gnueabi --sysroot=/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/usr/lib -shared -o libqevdevtabletplugin.so .obj/release-shared/main.o  -L/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/lib -L/opt/bsquask/build/qtbase-5.1.0/lib -lQt5PlatformSupport -lz -ludev -lEGL -lQt5Gui -lQt5Core -lGLESv2 -lpthread  
mv -f libqevdevtabletplugin.so ../../../../plugins/generic/ 
make[3]: **\* [sub-plugins-make_first] Error 2
make[2]: **\* [sub-src-make_first] Error 2
make[1]: **\* [/opt/bsquask/build/qtbase-5.1.0/.stamp_built] Error 2
make: **\* [all] Error 2

**Comment by nezticle** [comment]
This is quite unusual, but I don't actually see what caused the error here.  Could you paste some more of the output of this build error.  When building, buildroot is using as my CPU cores as you have available to build many things in parallel and this leads to misleading error output.  There is in fact an error, but it may be much further back in the terminal log.

**Comment by nezticle** [comment]
Ok, second question.  Are you doing "fresh" builds, or are these on top of an already existing build.

If so I must recommend doing "make clean" and building everything again from scratch (despite the fact that it takes forever).  BuildRoot can be very particular about this.

**Comment by lederer** [comment]
Thanks for the quick response. I'm doing fresh builds. Looks like this may be the real error:

../../../../mkspecs/devices/linux-rasp-pi-g++/qeglfshooks_pi.cpp:95:68: error: declaration of C function 'int vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T, DISPMANX_ELEMENT_HANDLE_T, uint32_t, int32_t, uint8_t, const VC_RECT_T_, const VC_RECT_T_, DISPMANX_RESOURCE_HANDLE_T, VC_IMAGE_TRANSFORM_T)' conflicts with
/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include/interface/vmcs_host/vc_dispmanx.h:108:22: error: previous declaration 'int vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T, DISPMANX_ELEMENT_HANDLE_T, uint32_t, int32_t, uint8_t, const VC_RECT_T_, const VC_RECT_T_, DISPMANX_RESOURCE_HANDLE_T, DISPMANX_TRANSFORM_T)' here
../../../../mkspecs/devices/linux-rasp-pi-g++/qeglfshooks_pi.cpp:195:10: warning: unused parameter 'window' [-Wunused-parameter]rm -f libqevdevtouchplugin.so
/opt/bsquask/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/lib -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib/arm-raspberrypi-linux-gnueabi -Wl,-rpath-link,/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/lib/arm-raspberrypi-linux-gnueabi --sysroot=/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/usr/lib -shared -o libqevdevtouchplugin.so .obj/release-shared/main.o  -L/opt/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/lib -L/opt/bsquask/build/qtbase-5.1.0/lib -lQt5PlatformSupport -lz -ludev -lEGL -lQt5Gui -lQt5Core -lGLESv2 -lpthread  

make[6]: **\* [.obj/release-shared/qeglfshooks_pi.o] Error 1
make[5]: **\* [sub-eglfs-make_first] Error 2
make[4]: **\* [sub-platforms-make_first] Error 2
make[4]: **\* Waiting for unfinished jobs....

**Comment by johnthesoftware** [comment]
Apparently the same issue I was having 8 days ago before Andy pushed new stuff.

This is a clean build. The errors seem identical to my original comment and to lederer's above

/home/johns/bsquask/host/usr/bin/arm-raspberrypi-linux-gnueabi-g++ -c -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot -O2 -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DQT_NO_XCB -DQT_NO_XKBCOMMON -DMESA_EGL_NO_X11_HEADERS -DEGLFS_PLATFORM_HOOKS -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PLATFORMSUPPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../../../mkspecs/devices/linux-rasp-pi-g++ -I. -I. -I/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include -I/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include/interface/vcos/pthreads -I/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include/interface/vmcs_host/linux -I../../../../include -I../../../../include/QtPlatformSupport -I../../../../include/QtPlatformSupport/5.1.0 -I../../../../include/QtPlatformSupport/5.1.0/QtPlatformSupport -I../../../../include/QtGui -I../../../../include/QtGui/5.1.0 -I../../../../include/QtGui/5.1.0/QtGui -I../../../../include/QtCore -I../../../../include/QtCore/5.1.0 -I../../../../include/QtCore/5.1.0/QtCore -I.moc/release-shared -I/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include -I/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include/interface/vcos/pthreads -I/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include/interface/vmcs_host/linux -o .obj/release-shared/qrc_cursor.o .rcc/release-shared/qrc_cursor.cpp
../../../../mkspecs/devices/linux-rasp-pi-g++/qeglfshooks_pi.cpp:95:68: error: declaration of C function 'int vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T, DISPMANX_ELEMENT_HANDLE_T, uint32_t, int32_t, uint8_t, const VC_RECT_T_, const VC_RECT_T_, DISPMANX_RESOURCE_HANDLE_T, VC_IMAGE_TRANSFORM_T)' conflicts with
/home/johns/bsquask/host/usr/arm-buildroot-linux-gnueabi/sysroot/opt/vc/include/interface/vmcs_host/vc_dispmanx.h:108:22: error: previous declaration 'int vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T, DISPMANX_ELEMENT_HANDLE_T, uint32_t, int32_t, uint8_t, const VC_RECT_T_, const VC_RECT_T_, DISPMANX_RESOURCE_HANDLE_T, DISPMANX_TRANSFORM_T)' here
../../../../mkspecs/devices/linux-rasp-pi-g++/qeglfshooks_pi.cpp:195:10: warning: unused parameter 'window' [-Wunused-parameter]
make[6]: **\* [.obj/release-shared/qeglfshooks_pi.o] Error 1
make[5]: **\* [sub-eglfs-make_first] Error 2
make[4]: **\* [sub-platforms-make_first] Error 2
make[3]: **\* [sub-plugins-make_first] Error 2
make[2]: **\* [sub-src-make_first] Error 2
make[1]: **\* [/home/johns/bsquask/build/qtbase-5.1.0/.stamp_built] Error 2

**Comment by nezticle** [comment]
Ah, I suppose anyone who bumps the firmware SHA1 is going to see this issue.  I purposely didn't monkey with the SHA1 for this update just in the interest of time (not having to spend another 3 hours testing).  What I'll do is push another default firmware/kernel/videocore update + a patch for qtbase.  Will have to find some time to do testing though.

**Comment by Tibalt** [comment]
@albertd I disable the export  like
+/*
 extern "C" int VCHPOST_ vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T update,
     DISPMANX_ELEMENT_HANDLE_T element, uint32_t change_flags, int32_t layer,
     uint8_t opacity, const VC_RECT_T *dest_rect, const VC_RECT_T *src_rect,

##      DISPMANX_RESOURCE_HANDLE_T mask, VC_IMAGE_TRANSFORM_T transform);

+*/

but no luck, the new error is:

./../../../mkspecs/devices/linux-rasp-pi-g++/qeglfshooks_pi.cpp:132:66: error: cannot convert 'VC_IMAGE_TRANSFORM_T' to 'DISPMANX_TRANSFORM_T' for argument '9' to 'int vc_dispmanx_element_change_attributes(DISPMANX_UPDATE_HANDLE_T, DISPMANX_ELEMENT_HANDLE_T, uint32_t, int32_t, uint8_t, const VC_RECT_T_, const VC_RECT_T_, DISPMANX_RESOURCE_HANDLE_T, DISPMANX_TRANSFORM_T)'

**Comment by nezticle** [comment]
I will try and push an update today that that has this error fixed as well as Qt 5.1.1.  It's almost done building now (just got to finish with QtWebkit), so when that is done I'll test and push up the change.

**Comment by nezticle** [comment]
Ok, try the lastest code.  qtbase should now have a small patch that fixes the issue.

**Comment by Tibalt** [comment]
@nezticle 
nice to catch update so early! test right now

**Comment by ghost** [comment]
Just did a complete rebuild with qtbase & wayland selected using the following revisions of firmware/userland/RaspberryPi-BuildRoot without any issues:

Raspberrypi/firmware https://github.com/raspberrypi/firmware/commit/d4f5315cfac4e14091d5440a6d482e033ba21b1b(2 sept 2013)
Raspberrypi/userland https://github.com/raspberrypi/userland/commit/b58a0498f1630008dd46c80686bd8fcff79e70ca (29 aug 2013)
RaspberryPi BuildRoot b92e4256b61a86e52011a85efb5b3063ca6ec70e (4 sep 2013)

**Comment by Tibalt** [comment]
compiled successfully
