### ISSUE TITLE
Image is very dim and blurred

### ISSUE THREAD

**Issue by azizazik** [nezticle/RaspberryPi-BuildRoot#53]
Observed when working with the PI via RCA connector image is very dim and blurred through hdmi dim, but not blurred. Editing /root/config.txt does not helps. What can be done? Monitor is working properly.

**Comment by ghost** [comment]
Could it be due to your rca cable? RCA is analog and interference might be picked up from other sources (RPi powersupply?) Maybe disabling overscan? Reports are that helped in some cases.

**Comment by azizazik** [comment]
RCA was somewhat different. Monitors also had a few.disabling overscan=1.I think because of the X11.Maybe not from this link.

**Comment by azizazik** [comment]
HDMI is good. RCA is  very dim and blurred
