### ISSUE TITLE
WiringPi

### ISSUE THREAD

**Issue by azizazik** [nezticle/RaspberryPi-BuildRoot#55]
If the clones or similar packages WiringPi, already in packages bsquask buildroots packeges. To work with Gpio, i2c,spi?

**Comment by ghost** [comment]
I've made some recipes, perhaps some will get you going:

https://github.com/limpens/WiringPi
https://github.com/limpens/pigpio

I add the contents of the PACKAGE directory to buildroot and include the necessary stuff to package/Config.in (the buildroot Makefile will include package/_/_.mk)

Personally I think pigpio is a nice way to add gpio to your programs.
