### ISSUE TITLE
WiFi

### ISSUE THREAD

**Issue by broberson** [nezticle/RaspberryPi-BuildRoot#56]
Quick question...

`lsmod` shows the driver for my USB wifi adapter is loaded, and `ifconfig wlan0 up` turns on the annoying little blue LED on the adapter, but there doesn't seem to be any wpa_supplicant installed, and none of this happens automatically on boot.

I'd like it to. It seems like wpa_supplicant is included in the build, but I can't find it on the generated rootfs anywhere. I'm not really reporting an issue here; just looking for a shove in the right direction.

Thanks Andy, for the great work, and for being so kind as to share it with the world. :)

**Comment by ghost** [comment]
I'm using wpa_supplicant like this:
- in make menuconfig select wpa_supplicant (package selection -> networking applications -> wpa_supplicant)
- use a custom recipe to 'customize' the target image and add a wpa_supplicant.conf to /etc/

I've changed some of the stuff in /etc/init, so wpa_supplicant is started when a new wlan interface is added:

-- /etc/init/wpa_supplicant.conf --
start on net-device-added INTERFACE=wlan0
stop on net-device-removed INTERFACE=wlan0

exec wpa_supplicant -Dwext -iwlan0 -c/etc/wpa_supplicant.conf

Eric.

**Comment by broberson** [comment]
Thanks very much, Eric. I'll give it a go.
