### ISSUE TITLE
Two Questions about Linux Kernel and Target Skeleton

### ISSUE THREAD

**Issue by MoJo2600** [nezticle/RaspberryPi-BuildRoot#60]
Hi there,

i have two small issues with the BuildRoot environment maybe somebody can give me a hint to resolve those.
1. I upgraded the kernel to use to 3.10 and created a custom kernel config and set the path in the buildroot configuration (as it is set in this BuildRoot). When i execute 'make linux-menuconfig', the configuration is read from this file, but the changes are not stored i the same file. Instead they are stored in $BSQUASK/build/linux-rpi-3.10.y/.config. So they get deleted every time i call 'make clean'. So what i do is, i always copy the .config file to BuildRoot/board/raspberrypi to have the changes stored and survive a 'make clean'. But that seams a little bit strange?
2. You provide a skeleton filesystem which is used for the target filesystem but when the filesystem is created not all files are copied. For example the files /etc/init.d/rcK and rcS are there, but the S20urandom and S40network are missing. I looked everywhere, but i did not find any script or setting which would delete those files afterwards... Did somebody experience something similar?

Thanks for any hint, regards

mojo

**Comment by ghost** [comment]
I suggest you take a look at the original Buildroot (http://buildroot.uclibc.org/) on which this environment was based. With the latest version you can add user defined packages and kernel configurations.

This repository is getting quite old and support for the RaspberryPi has been included in the original sometime ago.

Sincerely, Eric
