### ISSUE TITLE
Toolchain doesn't work older version of Ubuntu than 12.04

### ISSUE THREAD

**Issue by nezticle** [nezticle/RaspberryPi-BuildRoot#8]
I generated the toolchains in Ubuntu 12.04, and now there seems to be a hard dependency on GLIBC_2_14.

**Comment by ZeRaler** [comment]
Same problem.

I have to build my own toolchain with crosstool-ng & build.log from downloaded toolchain.
Once, I tweak raspberry-defconfig to take this toolchain.

BuildRoot compiles fine for me now.

**Comment by nezticle** [comment]
The Raspberry Pi guys provide a Crosstool-NG config for building your own toolchain here: https://github.com/raspberrypi/tools/blob/master/configs/bcm2708hardfp-ct-ng.config
in case anyone else is interested in building their own.
